CATEGORY_INFO = 2
CATEGORY_OTHER = 0
CATEGORY_USER = 1
CATEGORY_PROMOTION = 3
CATEGORY_STORE = 4

ACTION_OTHER = 0
ACTION_ADD = 1
ACTION_MODIFY = 2
ACTION_DELETE = 3
ACTION_SEARCH = 4
ACTION_LOGIN_IN = 5
ACTION_LOGIN_OUT = 6
ACTION_SCHEDULER = 7
